- name: Install dependencies
  apt:
    name:
      - curl
      - gnupg
      - apt-transport-https
    state: present

- name: Add RabbitMQ signing key
  shell: |
    curl -1sLf "https://keys.openpgp.org/vks/v1/by-fingerprint/0A9AF2115F4687BD29803A206B73A36E6026DFCA" | sudo gpg --dearmor | sudo tee /usr/share/keyrings/com.rabbitmq.team.gpg > /dev/null

- name: Add Erlang signing key
  shell: |
    curl -1sLf "{{ erlang_gpg_key_url }}" | sudo gpg --dearmor | sudo tee /usr/share/keyrings/rabbitmq.E495BB49CC4BBE5B.gpg > /dev/null

- name: Add RabbitMQ server signing key
  shell: |
    curl -1sLf "{{ rabbitmq_gpg_key_url }}" | sudo gpg --dearmor | sudo tee /usr/share/keyrings/rabbitmq.9F4587F226208342.gpg > /dev/null

- name: Add apt repositories
  shell: |
    echo "deb [arch=amd64 signed-by=/usr/share/keyrings/rabbitmq.E495BB49CC4BBE5B.gpg] {{ erlang_repo_url }}" | sudo tee /etc/apt/sources.list.d/rabbitmq.list
    echo "deb-src [signed-by=/usr/share/keyrings/rabbitmq.E495BB49CC4BBE5B.gpg] {{ erlang_repo_url }}" | sudo tee -a /etc/apt/sources.list.d/rabbitmq.list
    echo "deb [arch=amd64 signed-by=/usr/share/keyrings/rabbitmq.9F4587F226208342.gpg] {{ rabbitmq_repo_url }}" | sudo tee -a /etc/apt/sources.list.d/rabbitmq.list
    echo "deb-src [signed-by=/usr/share/keyrings/rabbitmq.9F4587F226208342.gpg] {{ rabbitmq_repo_url }}" | sudo tee -a /etc/apt/sources.list.d/rabbitmq.list

- name: Update package indices
  apt:
    update_cache: yes
    cache_valid_time: 3600
