- name: Update apt cache
  ansible.builtin.apt:
    update_cache: yes

- name: Install required system packages
  ansible.builtin.apt:
    name:
      - python3
      - libpq-dev
    state: present

- name: Install psycopg2
  ansible.builtin.apt:
    name: python3-psycopg2
    state: present

- name: Ensure required directory for PostgreSQL repository key exists
  ansible.builtin.file:
    path: /usr/share/postgresql-common/pgdg
    state: directory
    mode: '0755'

- name: Download the PostgreSQL repository key
  ansible.builtin.get_url:
    url: https://www.postgresql.org/media/keys/ACCC4CF8.asc
    dest: /usr/share/postgresql-common/pgdg/apt.postgresql.org.asc
    mode: '0644'

- name: Add PostgreSQL APT repository
  ansible.builtin.command:
    cmd: >
      sh -c 'echo "deb [signed-by=/usr/share/postgresql-common/pgdg/apt.postgresql.org.asc] https://apt.postgresql.org/pub/repos/apt {{ ansible_distribution_release }}-pgdg main" > /etc/apt/sources.list.d/pgdg.list'
    creates: /etc/apt/sources.list.d/pgdg.list

- name: Update apt cache again
  ansible.builtin.apt:
    update_cache: yes

- name: Install PostgreSQL
  ansible.builtin.apt:
    name: "postgresql-{{ postgresql_version }}"
    state: present

- name: Install PostgreSQL client and contrib packages
  ansible.builtin.apt:
    name:
      - "postgresql-client-{{ postgresql_version }}"
      - "postgresql-contrib-{{ postgresql_version }}"
    state: present

- name: Ensure PostgreSQL service is enabled and started
  ansible.builtin.service:
    name: postgresql
    state: started
    enabled: yes
