---
- name: Update Redis configuration to bind to all interfaces
  ansible.builtin.lineinfile:
    path: /etc/redis/redis.conf
    regexp: '^bind '
    line: 'bind 0.0.0.0'
    state: present

- name: Restart Redis service
  ansible.builtin.systemd:
    name: redis
    state: restarted
    enabled: yes

- name: Check Redis service status
  ansible.builtin.systemd:
    name: redis
    state: started
